apiVersion: v1
kind: Service
metadata:
  name: devops-api-service
spec:
  type: NodePort # Ouvre un port accessible pour le développement local
  selector:
    app: devops-api
  ports:
    - protocol: TCP
      port: 8000 # Port à l'intérieur du cluster
      targetPort: 8000 # Port de ton conteneur
      nodePort: 30007 # Port accessible depuis ton PC (entre 30000 et 32767)
